apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-ruby-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/pikitgb/test_argocd_sinatra_app 
    targetRevision: HEAD
    path: development

  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
