apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ruby-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-ruby-prod
  template:
    metadata:
      labels:
        app: app-ruby-prod
    spec:
      containers:
      - name: app-ruby-prod
        image: pikitgb/test-argo-cd:latest
        ports:
        - containerPort: 4567
