apiVersion: v1
kind: Service
metadata:
  name: app-ruby-prod-service
spec:
  selector:
    app: app-ruby-prod
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 4567
  type: LoadBalancer
